
name = "soundmaster-ai-chatbot"
main = "ai-chatbot.js"
compatibility_date = "2024-01-01"

[vars]
CLOUDFLARE_ACCOUNT_ID = "86e2b8822cebf8584cf942edb3103fae"

# KV Namespace for storing chat data
[[kv_namespaces]]
binding = "CHATBOT_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # Replace with your actual KV namespace ID

# AI binding
[[ai]]
binding = "AI"
